name: ESP-IDF Build

on:
  push:
    branches: [cn-localization, master]
  pull_request:
    branches: [cn-localization, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.1
          target: esp32

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: |
            build/esp32-wifi-penetration-tool.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
